apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

- ../apps/app1/deployment.yaml
- ../apps/app2/app2-kustomization.yaml
- ../apps/app3/app3-kustomization.yaml